services:
  web:
    build: .
    container_name: costumehub_web
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: "2.28.4.211,localhost,127.0.0.1"