# Generated by Django 6.0.7 on 2026-07-19 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_ilan_fotograf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sohbet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sohbetler', to='products.ilan')),
                ('ilan_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilan_sahibi_sohbetleri', to=settings.AUTH_USER_MODEL)),
                ('kiraci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiraci_sohbetleri', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sohbet',
                'verbose_name_plural': 'Sohbetler',
                'ordering': ['-guncellenme_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(max_length=1000)),
                ('okundu_mu', models.BooleanField(default=False)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('sohbet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='conversations.sohbet')),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['olusturulma_tarihi'],
            },
        ),
        migrations.AddConstraint(
            model_name='sohbet',
            constraint=models.UniqueConstraint(fields=('ilan', 'kiraci'), name='benzersiz_ilan_kiraci_sohbeti'),
        ),
    ]
