# Generated by Django 6.0.7 on 2026-07-18 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_ilan_fotograf'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KiralamaTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslangic_tarihi', models.DateField(verbose_name='Başlangıç tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş tarihi')),
                ('toplam_gun', models.PositiveIntegerField(verbose_name='Toplam gün')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam tutar')),
                ('durum', models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('KABUL_EDILDI', 'Kabul Edildi'), ('REDDEDILDI', 'Reddedildi'), ('IPTAL_EDILDI', 'İptal Edildi'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLIYOR', max_length=20, verbose_name='Talep durumu')),
                ('not_metni', models.TextField(blank=True, verbose_name='Kiracı notu')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma tarihi')),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiralama_talepleri', to='products.ilan', verbose_name='İlan')),
                ('kiraci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiralama_talepleri', to=settings.AUTH_USER_MODEL, verbose_name='Kiracı')),
            ],
            options={
                'verbose_name': 'Kiralama talebi',
                'verbose_name_plural': 'Kiralama talepleri',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
