# Generated by Django 6.0.7 on 2026-07-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiralamatalebi',
            name='durum',
            field=models.CharField(choices=[('BEKLIYOR', 'Bekliyor'), ('KABUL_EDILDI', 'Kabul Edildi'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('IADE_EDILDI', 'İade Edildi'), ('TAMAMLANDI', 'Tamamlandı'), ('REDDEDILDI', 'Reddedildi'), ('IPTAL_EDILDI', 'İptal Edildi')], default='BEKLIYOR', max_length=20, verbose_name='Talep durumu'),
        ),
    ]
