# Generated by Django 6.0.7 on 2026-07-19 18:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0002_alter_kiralamatalebi_durum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degerlendirme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('yorum', models.TextField(max_length=1000)),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('degerlendiren', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yaptigi_degerlendirmeler', to=settings.AUTH_USER_MODEL)),
                ('degerlendirilen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldigi_degerlendirmeler', to=settings.AUTH_USER_MODEL)),
                ('kiralama_talebi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='degerlendirme', to='rentals.kiralamatalebi')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
