# Generated by Django 6.0.7 on 2026-07-17 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Kategori adı')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=150, verbose_name='İlan başlığı')),
                ('aciklama', models.TextField(max_length=2000, verbose_name='Açıklama')),
                ('beden', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('STANDART', 'Standart')], max_length=20, verbose_name='Beden')),
                ('renk', models.CharField(max_length=50, verbose_name='Renk')),
                ('gunluk_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Günlük kiralama ücreti')),
                ('depozito', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Depozito')),
                ('sehir', models.CharField(max_length=50, verbose_name='Şehir')),
                ('durum', models.CharField(choices=[('TASLAK', 'Taslak'), ('YAYINDA', 'Yayında'), ('PASIF', 'Pasif')], default='YAYINDA', max_length=20, verbose_name='İlan durumu')),
                ('mevcut_mu', models.BooleanField(default=True, verbose_name='Kiralamaya uygun mu?')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('ilan_sahibi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilanlar', to=settings.AUTH_USER_MODEL, verbose_name='İlan sahibi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilanlar', to='products.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
