# Generated by Django 6.0.7 on 2026-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='fotograf',
            field=models.ImageField(blank=True, null=True, upload_to='ilanlar/', verbose_name='İlan fotoğrafı'),
        ),
    ]
