# Generated by Django 6.0.7 on 2026-07-20 07:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_ilan_fotograf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['sira', 'ad'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AddField(
            model_name='kategori',
            name='guncellenme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='olusturulma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturulma tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kategori',
            name='sira',
            field=models.PositiveIntegerField(default=0, help_text='Kategorilerin gösterim sırasını belirler.', verbose_name='Sıra'),
        ),
        migrations.AddField(
            model_name='kategori',
            name='ust_kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alt_kategoriler', to='products.kategori', verbose_name='Üst kategori'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='ad',
            field=models.CharField(max_length=100, verbose_name='Kategori adı'),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='URL adı'),
        ),
        migrations.AddConstraint(
            model_name='kategori',
            constraint=models.UniqueConstraint(condition=models.Q(('ust_kategori__isnull', True)), fields=('ad',), name='benzersiz_ana_kategori_adi'),
        ),
        migrations.AddConstraint(
            model_name='kategori',
            constraint=models.UniqueConstraint(condition=models.Q(('ust_kategori__isnull', True)), fields=('slug',), name='benzersiz_ana_kategori_slug'),
        ),
        migrations.AddConstraint(
            model_name='kategori',
            constraint=models.UniqueConstraint(condition=models.Q(('ust_kategori__isnull', False)), fields=('ust_kategori', 'ad'), name='benzersiz_alt_kategori_adi'),
        ),
        migrations.AddConstraint(
            model_name='kategori',
            constraint=models.UniqueConstraint(condition=models.Q(('ust_kategori__isnull', False)), fields=('ust_kategori', 'slug'), name='benzersiz_alt_kategori_slug'),
        ),
    ]
