# Generated by Django 6.0.7 on 2026-07-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_kategori_options_kategori_guncellenme_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriOzellik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Özellik adı')),
                ('veri_tipi', models.CharField(choices=[('SECIM', 'Seçim kutusu'), ('METIN', 'Metin'), ('SAYI', 'Sayı'), ('EVET_HAYIR', 'Evet / Hayır')], default='SECIM', max_length=20, verbose_name='Veri tipi')),
                ('zorunlu_mu', models.BooleanField(default=False, verbose_name='Zorunlu mu?')),
                ('filtrelenebilir_mi', models.BooleanField(default=True, help_text='Bu özellik ilan filtreleme alanında gösterilsin mi?', verbose_name='Filtrelenebilir mi?')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozellikler', to='products.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori özelliği',
                'verbose_name_plural': 'Kategori özellikleri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.CreateModel(
            name='OzellikSecenegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deger', models.CharField(max_length=100, verbose_name='Seçenek değeri')),
                ('aktif_mi', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('ozellik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='products.kategoriozellik', verbose_name='Özellik')),
            ],
            options={
                'verbose_name': 'Özellik seçeneği',
                'verbose_name_plural': 'Özellik seçenekleri',
                'ordering': ['sira', 'deger'],
            },
        ),
        migrations.CreateModel(
            name='IlanOzellikDegeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin_degeri', models.CharField(blank=True, max_length=255, verbose_name='Girilen değer')),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ozellik_degerleri', to='products.ilan', verbose_name='İlan')),
                ('ozellik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilan_degerleri', to='products.kategoriozellik', verbose_name='Özellik')),
                ('secenek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ilan_degerleri', to='products.ozelliksecenegi', verbose_name='Seçilen seçenek')),
            ],
            options={
                'verbose_name': 'İlan özellik değeri',
                'verbose_name_plural': 'İlan özellik değerleri',
            },
        ),
        migrations.AddConstraint(
            model_name='kategoriozellik',
            constraint=models.UniqueConstraint(fields=('kategori', 'ad'), name='benzersiz_kategori_ozelligi'),
        ),
        migrations.AddConstraint(
            model_name='ozelliksecenegi',
            constraint=models.UniqueConstraint(fields=('ozellik', 'deger'), name='benzersiz_ozellik_secenegi'),
        ),
        migrations.AddConstraint(
            model_name='ilanozellikdegeri',
            constraint=models.UniqueConstraint(fields=('ilan', 'ozellik'), name='ilanda_benzersiz_ozellik_degeri'),
        ),
    ]
