# Generated by Django 6.0.7 on 2026-07-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_kategoriozellik_ozelliksecenegi_ilanozellikdegeri_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IlanFotograf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotograf', models.ImageField(upload_to='ilanlar/', verbose_name='Fotoğraf')),
                ('ana_fotograf_mi', models.BooleanField(default=False, verbose_name='Ana fotoğraf mı?')),
                ('sira', models.PositiveIntegerField(default=0, verbose_name='Gösterim sırası')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ilan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='products.ilan', verbose_name='İlan')),
            ],
            options={
                'verbose_name': 'İlan fotoğrafı',
                'verbose_name_plural': 'İlan fotoğrafları',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
